{-# LANGUAGE UndecidableInstances #-}

-- |
-- Module      : $Header$
-- Description : First-class families for working with type-level 'Integral' numbers.
-- Copyright   : (c) Benoît Leulliette, 2026
-- License     : MIT
-- Maintainer  : benoit.leulliette@gmail.com
-- Stability   : provisional
-- Portability : portable
--
-- First-class families for working with type-level 'Integral' numbers.
module Obgs.Fcf.Integral
  ( -- * Construction
    Plus,
    PlusMaybe,
    Minus,
    MinusMaybe,
  )
where

import Fcf (Eval, Exp)
import Obgs.TL.Integral (TypeIntegral)
import Obgs.TL.Integral qualified as TI
import Obgs.TL.Nat (Nat)

-- See the note in 'Obgs.Fcf.Bool' for why the $setup block imports modules it does not use.

-- $setup
-- >>> :m +Fcf
-- >>> :m +Data.Int
-- >>> :m +Fcf.Data.Bool
-- >>> :m +Fcf.Utils
-- >>> :m +Obgs.Fcf.Bool
-- >>> :m +Obgs.Fcf.Maybe
-- >>> :m +Obgs.Fcf.Ord
-- >>> :m +Obgs.Fcf.Branch
-- >>> :m +Obgs.Fcf.Combinators
-- >>> :m +Obgs.TL.Maybe
-- >>> :m +Obgs.TL.Nat
-- >>> import Obgs.TL.Integral hiding (Plus, PlusMaybe, Minus, MinusMaybe)
--
-- The expression below is evaluated to force the bounds-checking machinery of
-- 'Obgs.TL.Integral' to load. Unlike every other module here, imports alone do
-- not reach it: those instances are generated by Template Haskell, and the
-- first expression to touch them comes back unreduced whichever one it is.
--
-- >>> :kind! (Eval (PlusMaybe 5) :: Maybe (TypeIntegral Int8))
-- ...

-- | A lifted variant of 'TI.Plus'.
data Plus :: Nat -> Exp (TypeIntegral a)

type instance Eval (Plus n) = TI.Plus n

-- | A lifted variant of 'TI.PlusMaybe'.
--
-- >>> :kind! (Eval (PlusMaybe 5) :: Maybe (TypeIntegral Int8))
-- ...
-- = Just ('Obgs.TL.Integral.Plus 4)
--
-- >>> :kind! (Eval (PlusMaybe 200) :: Maybe (TypeIntegral Int8))
-- ...
-- = Nothing
data PlusMaybe :: Nat -> Exp (Maybe (TypeIntegral a))

type instance Eval (PlusMaybe n) = TI.PlusMaybe n

-- | A lifted variant of 'TI.Minus'.
data Minus :: Nat -> Exp (TypeIntegral a)

type instance Eval (Minus n) = TI.Minus n

-- | A lifted variant of 'TI.MinusMaybe'.
--
-- >>> :kind! (Eval (MinusMaybe 200) :: Maybe (TypeIntegral Int8))
-- ...
-- = Nothing
data MinusMaybe :: Nat -> Exp (Maybe (TypeIntegral a))

type instance Eval (MinusMaybe n) = TI.MinusMaybe n